# config.py
BINANCE_API_KEY = "2wLrwX6OnmaMDuW3KQGQhMPpEEkpC0WpGNqb0jubKPAXfodBKzjqaMtNyaOE341P"
BINANCE_API_SECRET = "VVZYnAbe0QzsS8XRsl6kD8YGsuL7j4hOeW8F7MmXsKKxWWCg2Zth4OILpNBWJnvL"

TELEGRAM_TOKEN = "8449806355:AAFyzZhAVOf_6fVweRxUSYSYMxJAVWw_RcQ"
TELEGRAM_CHAT_ID = 658712542

# إعدادات التداول
POSITION_SIZE_PERCENT = 0.10   # 10% من الرصيد لكل صفقة
STOP_LOSS_PERCENT = 0.03       # 3% وقف خسارة
TAKE_PROFIT_PERCENT = 0.07     # 7% جني ربح

# السوق
UNIVERSE_MODE = "WHITELIST"
WHITELIST = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "ADAUSDT",
    "AVAXUSDT", "DOGEUSDT", "SHIBUSDT", "XRPUSDT", "LINKUSDT",
    "MATICUSDT", "DOTUSDT", "LTCUSDT", "TRXUSDT", "ATOMUSDT",
    "FTMUSDT", "NEARUSDT", "APTUSDT", "ARBUSDT", "OPUSDT",
    "RUNEUSDT", "INJUSDT", "SUIUSDT", "PEPEUSDT", "FLOKIUSDT",
    "WIFUSDT", "GRTUSDT", "1000SATSUSDT", "TWTUSDT", "BCHUSDT",
    "STXUSDT", "RNDRUSDT", "KASUSDT", "TIAUSDT", "JASMYUSDT",
    "ORDIUSDT", "SEIUSDT", "LDOUSDT", "IMXUSDT", "ARKMUSDT",
    "BOMEUSDT", "ENSUSDT", "DYDXUSDT", "SKLUSDT", "BLURUSDT",
    "SSVUSDT", "AGIXUSDT", "HOOKUSDT", "YGGUSDT", "OCEANUSDT"
]

SCAN_INTERVAL_SECONDS = 300  # كل 5 دقائق
MAX_CONCURRENT_POSITIONS = 3
