# render.yaml
services:
  - type: background
    name: binance-auto-trader
    env: python
    plan: starter  # مدفوع (Background Worker)
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot.py"
